SELECT DISTINCT ON (DEVICES.DEVICE_ID) DEVICES.DEVICE_ID,DEVICE_PAIRS.GATEWAY_ID,DEVICES.DEVICE_TOKEN,DEVICES.DEVICE_NAME 
FROM DEVICES
JOIN DEVICE_PAIRS ON DEVICE_PAIRS.DEVICE_ID = DEVICES.DEVICE_ID
JOIN TOILET_INFOS ON TOILET_INFOS.TOILET_INFO_ID = DEVICE_PAIRS.TOILET_INFO_ID
WHERE TOILET_INFOS.LOCATION_ID = '98998a6b-4be1-4ff4-5dd1-8a8e914943ee' AND DEVICES.DEVICE_TYPE_ID = 2



-- Select(distinct on (NOTIFICATION_DATA.NOTIFY_ID) NOTIFICATION_DATA.NOTIFY_ID,DEVICE_PAIRS.GATEWAY_ID,TOILET_INFOS.TOILET_INFO_ID,NOTIFICATION_DATA.FREQUENCY,NOTIFICATION_DATA.TOILET_TYPE_ID,FEEDBACK_PANELS.button_name as task_name,to_char(TIMESTAMP, 'YYYY-MM-DD')AS DATE , to_char(TIMESTAMP, 'HH24:MI:SS')  AS TIME).
Select NOTIFICATION_DATA.NOTIFY_ID, TIMESTAMP, NOTIFICATION_DATA.FREQUENCY, NOTIFICATION_DATA.TOILET_TYPE_ID,
 to_char(TIMESTAMP, 'YYYY-MM-DD')AS DATE , to_char(TIMESTAMP, 'HH24:MI:SS')  AS TIME, FEEDBACK_PANELS.button_name as task_name
FROM NOTIFICATION_DATA
JOIN FEEDBACK_PANELS ON FEEDBACK_PANELS.BUTTON_ID = NOTIFICATION_DATA.BUTTON_ID
JOIN DEVICES ON DEVICES.DEVICE_TOKEN = NOTIFICATION_DATA.DEVICE_TOKEN
-- Joins(JOIN DEVICE_PAIRS ON DEVICE_PAIRS.DEVICE_ID = DEVICES.DEVICE_ID).
-- Joins(JOIN TOILET_INFOS ON TOILET_INFOS.TOILET_INFO_ID = DEVICE_PAIRS.TOILET_INFO_ID).
-- Joins(JOIN LOCATIONS ON LOCATIONS.LOCATION_ID = TOILET_INFOS.LOCATION_ID).
JOIN TOILET_TYPES ON TOILET_TYPES.TOILET_TYPE_ID = NOTIFICATION_DATA.TOILET_TYPE_ID
-- Where(LOCATIONS.LOCATION_ID = ? AND NOTIFICATION_DATA.ACTION_STATUS = '0' AND TOILET_TYPES.TOILET_TYPE_ID IN (1,2),
-- 	locationID).
Where NOTIFICATION_DATA.ACTION_STATUS = '0' AND NOTIFICATION_DATA.DEVICE_TOKEN = '53'
ORDER BY NOTIFICATION_DATA.TIMESTAMP DESC



-- Select(distinct on (NOTIFICATION_DATA.NOTIFY_ID) NOTIFICATION_DATA.NOTIFY_ID,DEVICE_PAIRS.GATEWAY_ID,TOILET_INFOS.TOILET_INFO_ID,NOTIFICATION_DATA.FREQUENCY,NOTIFICATION_DATA.TOILET_TYPE_ID,FEEDBACK_PANELS.button_name as task_name,to_char(TIMESTAMP, 'YYYY-MM-DD')AS DATE , to_char(TIMESTAMP, 'HH24:MI:SS')  AS TIME).
SELECT NOTIFICATION_DATA.NOTIFY_ID, TIMESTAMP, NOTIFICATION_DATA.FREQUENCY, NOTIFICATION_DATA.TOILET_TYPE_ID, 
FEEDBACK_PANELS.button_name as task_name,to_char(TIMESTAMP, 'YYYY-MM-DD')AS DATE , 
to_char(TIMESTAMP, 'HH24:MI:SS')  AS TIME
FROM NOTIFICATION_DATA
JOIN FEEDBACK_PANELS ON FEEDBACK_PANELS.BUTTON_ID = NOTIFICATION_DATA.BUTTON_ID
JOIN DEVICES ON DEVICES.DEVICE_TOKEN = NOTIFICATION_DATA.DEVICE_TOKEN
-- Joins(JOIN DEVICE_PAIRS ON DEVICE_PAIRS.DEVICE_ID = DEVICES.DEVICE_ID).
-- Joins(JOIN TOILET_INFOS ON TOILET_INFOS.TOILET_INFO_ID = DEVICE_PAIRS.TOILET_INFO_ID).
-- Joins(JOIN LOCATIONS ON LOCATIONS.LOCATION_ID = TOILET_INFOS.LOCATION_ID).
JOIN TOILET_TYPES ON TOILET_TYPES.TOILET_TYPE_ID = NOTIFICATION_DATA.TOILET_TYPE_ID
-- Where(LOCATIONS.LOCATION_ID = ? AND NOTIFICATION_DATA.ACTION_STATUS = '0' AND TOILET_TYPES.TOILET_TYPE_ID IN (1,2),
-- 	locationID).
WHERE NOTIFICATION_DATA.ACTION_STATUS = '0' AND NOTIFICATION_DATA.DEVICE_TOKEN = '2'
ORDER BY NOTIFICATION_DATA.TIMESTAMP DESC