-- Active: 1720683458566@@127.0.0.1@5432@smarttoilet
-- mqtt info
SELECT * FROM mqtt_users

SELECT * FROM mqtt_users WHERE mqtt_users.tenant_id = '59944171-3a4a-460d-5897-8bb38c524d54'

-- get device pair
SELECT DEVICES.DEVICE_NAME,TOILET_TYPES.TOILET_TYPE_ID,DEVICES.DEVICE_ID,DEVICES.DEVICE_TOKEN,  
TOILET_INFOS.TOILET_NAME AS Identifier ,DEVICE_TYPES.DEVICE_TYPE_NAME AS Namespace  
FROM DEVICE_PAIRS  
JOIN DEVICES ON DEVICES.DEVICE_ID = DEVICE_PAIRS.DEVICE_ID  
JOIN DEVICE_TYPES ON DEVICE_TYPES.DEVICE_TYPE_ID = DEVICES.DEVICE_TYPE_ID  
JOIN TOILET_INFOS ON TOILET_INFOS.TOILET_INFO_ID = DEVICE_PAIRS.TOILET_INFO_ID  
JOIN TOILET_TYPES ON TOILET_TYPES.TOILET_TYPE_ID = TOILET_INFOS.TOILET_TYPE_ID  
WHERE GATEWAY_ID =(SELECT DEVICE_ID FROM DEVICES WHERE DEVICE_TOKEN = '39')

-- 					
Select DISTINCT  ON (toilet_infos.toilet_name)toilet_infos.toilet_name  AS IDENTIFIER ,TOILET_INFOS.TOILET_INFO_ID
FROM toilet_infos
JOIN TOILET_TYPES ON TOILET_TYPES.TOILET_TYPE_ID = TOILET_INFOS.TOILET_TYPE_ID
JOIN DEVICE_PAIRS ON DEVICE_PAIRS.TOILET_INFO_ID = TOILET_INFOS.TOILET_INFO_ID
Where DEVICE_PAIRS.GATEWAY_ID = '1b24efde-fb72-4849-4a04-89757b9550a5'

