WITH
    NOW_ENV AS (
        SELECT *
        FROM ENVIROMENT_DATA
        WHERE
            ENVIROMENT_DATA.TIMESTAMP BETWEEN CURRENT_TIMESTAMP - INTERVAL '1 DAY' AND CURRENT_TIMESTAMP
    ),
    USER_REACT AS (
        SELECT *
        FROM USER_REACTIONS
        WHERE
            USER_REACTIONS.TIMESTAMP BETWEEN CURRENT_TIMESTAMP - INTERVAL '1 DAY' AND CURRENT_TIMESTAMP
    )
SELECT AVG(USER_REACT.SCORE) AS SCORE, LOCATIONS.*, AVG(NOW_ENV.IAQ) AS IAQ
FROM
    LOCATIONS
    LEFT JOIN TOILET_INFOS ON TOILET_INFOS.LOCATION_ID = LOCATIONS.LOCATION_ID
    LEFT JOIN USER_REACT ON USER_REACT.TOILET_ID = TOILET_INFOS.toilet_info_id
    LEFT JOIN DEVICE_PAIRS ON DEVICE_PAIRS.TOILET_INFO_ID = TOILET_INFOS.TOILET_INFO_ID
    LEFT JOIN DEVICES ON DEVICES.DEVICE_ID = DEVICE_PAIRS.DEVICE_ID
    LEFT JOIN NOW_ENV on NOW_ENV.DEVICE_TOKEN = DEVICES.DEVICE_TOKEN
WHERE
    LOCATIONS.DEV_MODE = 'no'
    AND LOCATIONS.TENANT_ID = '59944171-3a4a-460d-5897-8bb38c524d54'
GROUP BY
    LOCATIONS.LOCATION_ID