
-- Create the table with an id column using UUID
CREATE TABLE carbon_emmision (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
    Country VARCHAR(50),
    CO2_kg_per_kWh DECIMAL(5, 3)
);

-- Insert the data (id will be auto-generated by uuid_generate_v4())
INSERT INTO
    carbon_emmision (Country, CO2_kg_per_kWh)
VALUES ('Sweden', 0.013),
    ('Lithuania', 0.018),
    ('France', 0.059),
    ('Austria', 0.085),
    ('Latvia', 0.105),
    ('Finland', 0.113),
    ('Slovakia', 0.132),
    ('Denmark', 0.166),
    ('Belgium', 0.170),
    ('Croatia', 0.210),
    ('Luxembourg', 0.219),
    ('Slovenia', 0.254),
    ('Italy', 0.256),
    ('Hungary', 0.260),
    ('Spain', 0.265),
    ('UnitedKingdom', 0.281),
    (
        'EuropeanUnion(currentcomposition)',
        0.296
    ),
    ('Romania', 0.306),
    ('Portugal', 0.325),
    ('Ireland', 0.425),
    ('Germany', 0.441),
    ('Bulgaria', 0.470),
    ('Netherlands', 0.505),
    ('Czechia', 0.513),
    ('Greece', 0.623),
    ('Malta', 0.648),
    ('Cyprus', 0.677),
    ('Poland', 0.773),
    ('Estonia', 0.819);


    select * from carbon_emmision